---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: argocd-and-user-service-ingress
  namespace: backcd  # ArgoCD와 user-service가 같은 네임스페이스에 있다고 가정
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/proxy-body-size: 50m
spec:
  tls:
  - hosts:
    - ssafy11s.com
    secretName: argocd-server-tls
  rules:
  - host: ssafy11s.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: argocd-server
            port:
              number: 80
      - path: /api
        pathType: Prefix
        backend:
          service:
            name: user-service
            port:
              number: 80

---
apiVersion: v1
kind: Service
metadata:
  name: user-service
  namespace: backcd  # 기존 네임스페이스 유지
spec:
  type: NodePort  # 서비스 타입을 NodePort로 변경
  selector:
    app: user-service
  ports:
    - protocol: TCP
      port: 80  # 클러스터 내부에서 사용할 포트
      targetPort: 8080  # 컨테이너의 포트
      nodePort: 30080  # 외부에서 접근할 포트 (30000-32767 범위)