apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway-service
  namespace: backcd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gateway-service
  template:
    metadata:
      labels:
        app: gateway-service
    spec:
      securityContext:
        runAsUser: 1000  # 컨테이너에서 사용하는 사용자 ID
        runAsGroup: 1000  # 그룹 ID
        fsGroup: 1000     # 볼륨에 접근할 때 사용할 그룹 ID
      initContainers:
        - name: init-apm-agent
          image: curlimages/curl:latest  # Curl 이미지를 사용하여 JAR 파일을 다운로드
          command:
            - "sh"
            - "-c"
            - >
              curl -o /elastic/elastic-apm-agent.jar https://repo1.maven.org/maven2/co/elastic/apm/elastic-apm-agent/1.51.0/elastic-apm-agent-1.51.0.jar;
          volumeMounts:
            - name: elastic-apm-volume
              mountPath: /elastic  # APM 에이전트 파일을 저장할 경로
      containers:
        - name: gateway-service
          image: zlxldgus123/gateway-service:274
          ports:
            - containerPort: 8080
          env:
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: secret
            - name: JAVA_TOOL_OPTIONS
              value: "-javaagent:/elastic/elastic-apm-agent.jar -Delastic.apm.service_name=gateway-service -Delastic.apm.server_urls=http://10.104.2.1:8200 -Delastic.apm.application_packages=com.sog -Delastic.apm.use_path_as_transaction_name=true -Delastic.apm.transaction_name_groups=/api/user/\\d+,/api/stock/\\d+,/api/news/\\d+"
          volumeMounts:
            - name: elastic-apm-volume
              mountPath: /elastic  # APM 에이전트가 위치할 경로
          resources:
            requests:
              memory: "125Mi"  # 최소 메모리 요청
            limits:
              memory: "250Mi"  # 최대 메모리 제한
      volumes:
        - name: elastic-apm-volume
          emptyDir: {}  # 파드 내 임시 디렉터리 사용
