apiVersion: v1
kind: Service
metadata:
  name: gateway-service
  namespace: backcd
spec:
  type: ClusterIP  # NodePort에서 ClusterIP로 변경
  selector:
    app: gateway-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080  # 클러스터 내부에서 사용할 포트 매핑
