apiVersion: apps/v1
kind: Deployment
metadata:
  name: news-service
  namespace: backcd
spec:
  replicas: 2  # 기본 레플리카 수, HPA 사용 시 동적으로 조정 가능
  selector:
    matchLabels:
      app: news-service
  template:
    metadata:
      labels:
        app: news-service
    spec:
      securityContext:
        runAsUser: 1000  # 컨테이너에서 사용하는 사용자 ID
        runAsGroup: 1000  # 그룹 ID
        fsGroup: 1000     # 볼륨에 접근할 때 사용할 그룹 ID
      initContainers:
        - name: init-apm-agent
          image: curlimages/curl:latest  # Curl 이미지를 사용하여 JAR 파일을 다운로드
          command:
            - "sh"
            - "-c"
            - >
              curl -o /elastic/elastic-apm-agent.jar https://repo1.maven.org/maven2/co/elastic/apm/elastic-apm-agent/1.51.0/elastic-apm-agent-1.51.0.jar;
          volumeMounts:
            - name: elastic-apm-volume
              mountPath: /elastic  # APM 에이전트 파일을 저장할 경로
      containers:
        - name: news-service
          image: zlxldgus123/news-service:248
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:mysql://mysql:3306/sog_db
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: db-secrets
                  key: username
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secrets
                  key: password
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: secret
            - name: JAVA_TOOL_OPTIONS
              value: "-javaagent:/elastic/elastic-apm-agent.jar -Delastic.apm.service_name=news-service -Delastic.apm.server_urls=http://10.105.247.180:8200 -Delastic.apm.application_packages=com.sog -Delastic.apm.use_path_as_transaction_name=true -Delastic.apm.transaction_name_groups=/api/user/\\d+,/api/stock/\\d+,/api/news/\\d+"
          volumeMounts:
            - name: elastic-apm-volume
              mountPath: /elastic  # APM 에이전트가 위치할 경로
          resources:  # 리소스 요청 및 제한 설정
            requests:
              memory: "512Mi"
              cpu: "250m"
            limits:
              memory: "1Gi"
              cpu: "500m"
      volumes:
        - name: elastic-apm-volume
          emptyDir: {}  # 파드 내 임시 디렉터리 사용
