spring:
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/api/users/**
        - id: stock-service
          uri: lb://stock-service
          predicates:
            - Path=/api/stocks/**
        - id: news-service
          uri: lb://news-service
          predicates:
            - Path=/api/news/**

jwt:
  secret: ${JWT_SECRET}  # Kubernetes Secret?? ???? JWT ???
