spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true  # 서비스 디스커버리 활성화
      routes:
        - id: gateway-status
          uri: http://localhost:8080  # Gateway 서비스 자체의 주소
          predicates:
            - Path=/status
        - id: user-service
          uri: http://user-service.backcd.svc.cluster.local:80
          predicates:
            - Path=/api/user/**
        - id: user-service-swagger
          uri: http://user-service.backcd.svc.cluster.local:80
          predicates:
            - Path=/api/user/swagger-ui/**
          filters:
            - RewritePath=/api/user/swagger-ui(?<segment>/?.*), /swagger-ui${segment}  # Swagger UI 경로 재작성
        - id: stock-service
          uri: http://stock-service.backcd.svc.cluster.local:80
          predicates:
            - Path=/api/stock/**
        - id: stock-service-swagger
          uri: http://stock-service.backcd.svc.cluster.local:80
          predicates:
            - Path=/api/stock/swagger-ui/**
          filters:
            - RewritePath=/api/stock/swagger-ui(?<segment>/?.*), /swagger-ui${segment}  # Swagger UI 경로 재작성
        - id: news-service
          uri: http://news-service.backcd.svc.cluster.local:80
          predicates:
            - Path=/api/news/**
        - id: news-service-swagger
          uri: http://news-service.backcd.svc.cluster.local:80
          predicates:
            - Path=/api/news/swagger-ui/**
          filters:
            - RewritePath=/api/news/swagger-ui(?<segment>/?.*), /swagger-ui${segment}  # Swagger UI 경로 재작성

jwt:
  secret: "3c84e62c46e5438e9d12e28a9876591bc34e4e92a3a489b749ab2d9c9e367d89"  # Kubernetes Secret에서 JWT 가져오기

management:
  endpoints:
    web:
      exposure:
        include: gateway, health  # 유효한 엔드포인트 이름
  endpoint:
    health:
      show-details: always  # 헬스체크에서 자세한 정보 제공

logging:
  level:
    com.example.gateway.config.LoggingFilterConfig: DEBUG  # 필터 로그를 디버그 레벨로 설정
    org.springframework.cloud.gateway: DEBUG  # Spring Cloud Gateway 전체 디버그 로그
