spring:
  data:
    redis:
      host: redis
      port: 6379      # Redis 서버의 포트 번호
  cloud:
    gateway:
      filter:
        remove-non-proxy-headers:
          headers:
            - Proxy-Authenticate
            - Proxy-Authorization
            - Keep-Alive
            - TE
            - Trailer
            - Transfer-Encoding
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "https://ssafy11s.com"
              - "http://localhost:3000"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders:
              - "Content-Type"
              - "Authorization"
              - "X-Requested-With"
              - "Accept"
            allowCredentials: true
            maxAge: 3600
      routes:
        - id: user-service
          uri: http://user-service.backcd.svc.cluster.local:80
          predicates:
            - Path=/api/user/**
          filters:
            - CachingGatewayFilterFactory # 캐싱 필터 적용

        - id: stock-service
          uri: http://stock-service.backcd.svc.cluster.local:80
          predicates:
            - Path=/api/stock/**
          filters:
            - CachingGatewayFilterFactory # 캐싱 필터 적용

        - id: news-service
          uri: http://news-service.backcd.svc.cluster.local:80
          predicates:
            - Path=/api/news/**
          filters:
            - CachingGatewayFilterFactory # 캐싱 필터 적용

jwt:
  secret: ${JWT_SECRET:default-secret}

management:
  endpoints:
    web:
      exposure:
        include: gateway, health
  endpoint:
    health:
      show-details: always

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
