spring:
  application:
    name: sog-news
  datasource:
    url: jdbc:mysql://localhost:3306/sog_db
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        jdbc:
          time_zone: Asia/Seoul
    show-sql: true
  data:
    mongodb:
      uri: mongodb://3.38.183.146:30017/topic
#    redis:
#      host: redis
#      port: 6379

logging:
  level:
    org:
      hibernate:
        SQL: debug

server:
  port: 8080  # ?? ??? 8081? ??
  timezone: Asia/Seoul
  error:
    include-message: always
    include-binding-errors: always
  tomcat:
    uri-encoding: UTF-8
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

management:
  endpoints:
    web:
      exposure:
        include: health, prometheus
  metrics:
    export:
      prometheus:
        enabled: true
  endpoint:
    prometheus:
      enabled: true