apiVersion: apps/v1
kind: Deployment
metadata:
  name: apm-server
  namespace: dev  # 필요한 네임스페이스로 수정
spec:
  replicas: 1
  selector:
    matchLabels:
      app: apm-server
  template:
    metadata:
      labels:
        app: apm-server
    spec:
      containers:
        - name: apm-server
          image: docker.elastic.co/apm/apm-server:8.3.2
          ports:
            - containerPort: 8200
          env:
            - name: ELASTICSEARCH_HOSTS
              value: "http://elasticsearch:9200"
            - name: ELASTICSEARCH_USERNAME
              value: "elastic"
            - name: ELASTICSEARCH_PASSWORD
              value: "ua8747ll"  # Elasticsearch 비밀번호
            - name: KIBANA_HOST
              value: "http://3.38.183.146:30056"
            - name: KIBANA_USERNAME
              value: "kibana_system"
            - name: KIBANA_PASSWORD
              value: "ua8747ll"  # Kibana 비밀번호
          command: ["/usr/share/apm-server/apm-server", "-e", "-E", "output.elasticsearch.hosts=${ELASTICSEARCH_HOSTS}", "-E", "output.elasticsearch.username=${ELASTICSEARCH_USERNAME}", "-E", "output.elasticsearch.password=${ELASTICSEARCH_PASSWORD}", "-E", "setup.kibana.host=${KIBANA_HOST}", "-E", "setup.kibana.username=${KIBANA_USERNAME}", "-E", "setup.kibana.password=${KIBANA_PASSWORD}", "-E", "apm-server.host=0.0.0.0:8200", "-E", "http.host=0.0.0.0", "-E", "http.port=8200"]
---
apiVersion: v1
kind: Service
metadata:
  name: apm-server
  namespace: dev  # 필요한 네임스페이스로 수정
spec:
  type: NodePort
  ports:
    - port: 8200
      targetPort: 8200
      nodePort: 30192
  selector:
    app: apm-server
