# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: apm-server
#   namespace: dev  # 필요한 네임스페이스로 수정
# spec:
#   replicas: 1
#   selector:
#     matchLabels:
#       app: apm-server
#   template:
#     metadata:
#       labels:
#         app: apm-server
#     spec:
#       containers:
#         - name: apm-server
#           image: docker.elastic.co/apm/apm-server:8.3.2
#           ports:
#             - containerPort: 8200
#           volumeMounts:
#             - name: apm-server-config-volume
#               mountPath: /etc/apm-server/apm-server.yml
#               subPath: apm-server.yml
#       volumes:
#         - name: apm-server-config-volume
#           configMap:
#             name: apm-server-config  # APM 서버 ConfigMap 이름

# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: apm-server
#   namespace: dev  # 필요한 네임스페이스로 수정
# spec:
#   type: NodePort
#   ports:
#     - port: 8200
#       targetPort: 8200
#       nodePort: 30192
#   selector:
#     app: apm-server
