apiVersion: apps/v1
kind: Deployment
metadata:
  name: apm-server
  namespace: dev
  labels:
    app: apm-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: apm-server
  template:
    metadata:
      labels:
        app: apm-server
    spec:
      containers:
        - name: apm-server
          image: docker.elastic.co/apm/apm-server:7.15.0
          ports:
            - containerPort: 8200
          env:
            - name: ELASTIC_APM_USERNAME
              value: "elastic"
            - name: ELASTIC_APM_PASSWORD
              value: "ua8747ll"
            - name: APMSERVER_CONFIG  # APM 서버 설정을 직접 환경 변수로 정의
              value: |
                apm-server:
                  host: "0.0.0.0:8200"
                output.elasticsearch:
                  hosts: ["http://10.109.249.133:9200"]
                logging:
                  level: info
                setup.template.enabled: true
          command: ["apm-server"]  # 설정 파일 없이 기본 실행
---
apiVersion: v1
kind: Service
metadata:
  name: apm-server
  namespace: dev
spec:
  selector:
    app: apm-server
  type: NodePort
  ports:
    - protocol: TCP
      port: 8200          # APM 서버의 기본 포트
      targetPort: 8200     # 컨테이너 내부의 포트
      nodePort: 30880      # NodePort로 노출할 포트 (30000-32767 범위에서 지정 가능)
