apiVersion: apps/v1
kind: Deployment
metadata:
  name: apm-server
  namespace: dev
  labels:
    app: apm-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: apm-server
  template:
    metadata:
      labels:
        app: apm-server
    spec:
      containers:
        - name: apm-server
          image: docker.elastic.co/apm/apm-server:8.15.2
          ports:
            - containerPort: 8200
          env:
            - name: ELASTIC_APM_USERNAME
              value: "elastic"
            - name: ELASTIC_APM_PASSWORD
              value: "ua8747ll"
            - name: APMSERVER_CONFIG
              value: |
                apm-server:
                  host: "0.0.0.0:8200"
                output.elasticsearch:
                  hosts: ["http://10.109.249.133:9200"]
                logging:
                  level: debug
                setup.template.enabled: true
          command: ["apm-server"]  # 설정 파일을 따로 지정하지 않고 기본 실행
---
apiVersion: v1
kind: Service
metadata:
  name: apm-server
  namespace: dev
spec:
  selector:
    app: apm-server
  type: NodePort
  ports:
    - protocol: TCP
      port: 8200
      targetPort: 8200
      nodePort: 30880
