apiVersion: apps/v1
kind: Deployment
metadata:
  name: apm-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: apm-server
  template:
    metadata:
      labels:
        app: apm-server
    spec:
      containers:
        - name: apm-server
          image: docker.elastic.co/apm/apm-server-arm64:7.3.2
          ports:
            - containerPort: 8200
          env:
            - name: ELASTICSEARCH_HOSTS
              value: http://elasticsearch:9200
---
apiVersion: v1
kind: Service
metadata:
  name: apm-server
spec:
  type: NodePort
  ports:
    - port: 8200
      targetPort: 8200
      nodePort: 30192
  selector:
    app: apm-server
