apiVersion: v1
kind: PersistentVolume
metadata:
  name: elastic-apm-pv
  namespace: backcd
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: standard
  hostPath:
    path: "/mnt/data/elastic-apm"  # 노드의 특정 경로
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: elastic-apm-pvc
  namespace: backcd
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: standard
