apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: elasticsearch
spec:
  serviceName: "elasticsearch"
  replicas: 1
  selector:
    matchLabels:
      app: elasticsearch
  template:
    metadata:
      labels:
        app: elasticsearch
    spec:
      securityContext:
        runAsUser: 1001        # elasticsearch 사용자 UID
        fsGroup: 1001          # elasticsearch 그룹 GID
      containers:
        - name: elasticsearch
          image: docker.elastic.co/elasticsearch/elasticsearch:8.3.2
          ports:
            - containerPort: 9200
              name: http
          volumeMounts:
            - name: elasticsearch-data
              mountPath: /var/lib/elasticsearch/data   # 데이터 경로 변경
          env:
            - name: discovery.type
              value: single-node
            - name: xpack.security.enabled
              value: "true"  # 보안 활성화
            - name: xpack.security.authc.api_key.enabled
              value: "false"  # API 키 인증 활성화
      volumes:
        - name: elasticsearch-data
          persistentVolumeClaim:
            claimName: elasticsearch-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: elasticsearch
spec:
  type: NodePort
  ports:
    - port: 9200
      targetPort: 9200
      nodePort: 30193
  selector:
    app: elasticsearch
