apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-deployment
  namespace: backcd  # 네임스페이스 지정
spec:
  replicas: 1  # 필요 시 레플리카 수 조정
  selector:
    matchLabels:
      app: kafka
  template:
    metadata:
      labels:
        app: kafka
    spec:
      containers:
        - name: kafka
          image: bitnami/kafka:latest  # Bitnami Kafka 이미지 사용
          ports:
            - containerPort: 9092  # Kafka 기본 포트
          env:
            # Zookeeper 연결 설정
            - name: KAFKA_CFG_ZOOKEEPER_CONNECT
              value: "zookeeper-service:2181"
            # 외부에서 Kafka에 접근할 수 있도록 advertised.listeners 설정
            - name: KAFKA_CFG_ADVERTISED_LISTENERS
              value: "PLAINTEXT://3.38.183.146:30092"  # INTERNAL IP와 NodePort 사용
            # 인증 없이 접근 허용 (로컬 테스트 환경)
            - name: ALLOW_PLAINTEXT_LISTENER
              value: "yes"
          resources:
            requests:
              memory: "512Mi"  # 최소 메모리 요청
            limits:
              memory: "1Gi"    # 최대 메모리 사용량 1Gi로 제한
          volumeMounts:
            - name: kafka-storage
              mountPath: /bitnami/kafka  # Kafka 데이터 저장 경로
      volumes:
        - name: kafka-storage
          persistentVolumeClaim:
            claimName: kafka-pvc  # PVC에 맞게 설정


---
apiVersion: v1
kind: Service
metadata:
  name: kafka-service
  namespace: backcd  # 네임스페이스 지정
spec:
  type: NodePort
  ports:
    - port: 9092  # Kafka 기본 포트
      targetPort: 9092
      nodePort: 30092  # 외부 노출을 위한 포트
  selector:
    app: kafka
