apiVersion: apps/v1
kind: Deployment
metadata:
  name: kibana
  namespace: dev  # 필요한 네임스페이스로 수정
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kibana
  template:
    metadata:
      labels:
        app: kibana
    spec:
      containers:
        - name: kibana
          image: docker.elastic.co/kibana/kibana:7.3.2
          ports:
            - containerPort: 5601
          volumeMounts:
            - name: kibana-config-volume
              mountPath: /usr/share/kibana/config/kibana.yml
              subPath: kibana.yml
      volumes:
        - name: kibana-config-volume
          configMap:
            name: kibana-config  # Kibana ConfigMap 이름

---
apiVersion: v1
kind: Service
metadata:
  name: kibana
  namespace: dev  # 필요한 네임스페이스로 수정
spec:
  type: NodePort
  ports:
    - port: 5601
      targetPort: 5601
      nodePort: 30056
  selector:
    app: kibana
