apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: loki-pv-claim
  namespace: monitoring  # Loki가 설치된 네임스페이스
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi  # PV의 용량과 일치
  storageClassName: standard
