---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongodb-pv-claim
  namespace: backcd
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  storageClassName: standard
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongodb-pv-node1
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: standard
  hostPath:
    path: "/mnt/data/mongodb"  # MongoDB 데이터를 저장할 로컬 경로
  nodeAffinity:  # 특정 노드에 바인딩
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - ip-172-26-0-238  # 특정 노드 IP 설정
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb
  namespace: backcd
  labels:
    app: mongodb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
      - name: mongodb
        image: mongo:5.0  # MongoDB 5.0 이미지
        ports:
        - containerPort: 27017
        volumeMounts:
        - name: mongodb-storage
          mountPath: /data/db  # MongoDB의 데이터 저장 경로
      volumes:
      - name: mongodb-storage
        persistentVolumeClaim:
          claimName: mongodb-pv-claim
