apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: backcd
spec:
  ports:
  - port: 3306
    targetPort: 3306
    nodePort: 32000 # 원하는 포트를 설정 (옵션)
  selector:
    app: mysql
  type: NodePort
