# apiVersion: v1
# kind: ConfigMap
# metadata:
#   name: mysql-init-script
#   namespace: backcd  # 네임스페이스 추가
# data:
#   init.sql: |
#     CREATE DATABASE IF NOT EXISTS sog_db;

# ---
# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: mysql
#   namespace: backcd  # 네임스페이스 추가
#   labels:
#     app: mysql
# spec:
#   replicas: 1
#   selector:
#     matchLabels:
#       app: mysql
#   template:
#     metadata:
#       labels:
#         app: mysql
#     spec:
#       containers:
#       - name: mysql
#         image: mysql:8.0
#         env:
#         - name: MYSQL_ROOT_PASSWORD
#           value: "rootpassword"  # MySQL root 비밀번호
#         - name: MYSQL_DATABASE
#           value: "sog_db"  # 자동으로 생성할 데이터베이스 이름
#         ports:
#         - containerPort: 3306
#         volumeMounts:
#         - name: mysql-storage
#           mountPath: /var/lib/mysql
#         - name: mysql-init-script
#           mountPath: /docker-entrypoint-initdb.d
#         resources:
#           limits:
#             memory: "4Gi"  # 메모리 제한 4Gi
#           requests:
#             memory: "2Gi"  # 최소 요청 메모리 2Gi (조정 가능)
#       volumes:
#       - name: mysql-storage
#         persistentVolumeClaim:
#           claimName: mysql-pv-claim
#       - name: mysql-init-script
#         configMap:
#           name: mysql-init-script
#       nodeSelector:
#         kubernetes.io/hostname: ip-172-26-0-238
#       tolerations:
#       - key: "node-role.kubernetes.io/control-plane"
#         operator: "Exists"
#         effect: "NoSchedule"
