apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  labels:
    app: frontend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: zlxldgus123/frontend:latest  # Docker 이미지
        ports:
        - containerPort: 80
        env:
        - name: ENVIRONMENT
          value: "production"
