spring:
  application:
    name: sog

  datasource:
    url: jdbc:mysql://localhost:3306/sog_db
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: ed9658pi
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        jdbc:
          time_zone: UTC
    show-sql: true

logging:
  level:
    org:
      hibernate:
        SQL: debug

kis:
  appkey: "PSji3Tn79KSAKz0msD1dldUIXNre9JhlcJ2M"
  appsecret: "q5OxO241o89X0qoz+6i0Zh7+Xvg4nSHEvFdpU7KYJECpnJ4I4L9Lxp56kZVfU3XsKiuRm5FcmFMB5pPEq+RPlLl6pHo3YIPUdX33OZW+tq7VXE89BYwzqCCrqnL+8Efn/srraX6maHl+nPwJOYkn2tjst628ltU0w82nB7l0iDrXBkNXGJY="
  websocket:
    domain: "ws://ops.koreainvestment.com:21000"
    approval_key: "25b57418-f962-4287-b815-5e8114506c69"

server:
  error:
    include-message: always
    include-binding-errors: always
