spring:
  application:
    name: sog

  datasource:
    url: jdbc:mysql://localhost:3306/sog_db
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: rootpassword
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        jdbc:
          time_zone: UTC
    show-sql: true
  data:
    redis:
      host: redis
      port: 6379

logging:
  level:
    org:
      hibernate:
        SQL: debug

kis:
  realtime-stock:
    appkey: "PSji3Tn79KSAKz0msD1dldUIXNre9JhlcJ2M"
    appsecret: "q5OxO241o89X0qoz+6i0Zh7+Xvg4nSHEvFdpU7KYJECpnJ4I4L9Lxp56kZVfU3XsKiuRm5FcmFMB5pPEq+RPlLl6pHo3YIPUdX33OZW+tq7VXE89BYwzqCCrqnL+8Efn/srraX6maHl+nPwJOYkn2tjst628ltU0w82nB7l0iDrXBkNXGJY="
  chart:
    appkey: "PSTVy2mFMMrHQ97LAnfgRVcI5zRr7p3JGOxo"
    appsecret: "JmbcXXasdhSxCWqzQDV3/2BG5plUGGL+udWU+uL+coAQ08pUxnliNdQU+8XrFsmjBqIqXsju7g4s/sQ+dkanRVTfZwmF16aQ2GT4RNZdXHR5+2j9EFv3JymNiTcGbpdcXuX2LJOa8/vSAdgBV3XvYLBbLfhlB+TW+nZbR+6sz2b5hANZ7Jw="

server:
  error:
    include-message: always
    include-binding-errors: always
